import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-vivo-x300-pro',
    slug: 'vivo-x300-pro',
    name: 'vivo X300 Pro',
    brand: 'vivo',
    description: 'Co-engineered with ZEISS optics, featuring 200MP APO Telephoto camera, MediaTek Dimensity 9400, and 6000mAh battery in Crimson Red finish.',
    createdAt: new Date('2026-02-20T00:00:00Z'),
    variants: [
      {
        id: 'var-vx300-256-red',
        productId: 'prod-vivo-x300-pro',
        label: '256GB / Crimson Red',
        storage: '256GB',
        color: 'Crimson Red',
        imageUrl: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=800&q=80',
        mrp: 99999,
        price: 89999,
        stock: 40,
        emiPlans: [
          {
            id: 'emi-vx300-256r-3m',
            variantId: 'var-vx300-256-red',
            tenureMonths: 3,
            monthlyAmount: 29999,
            interestRate: 0,
            cashbackAmount: 5000,
            cashbackNote: 'Additional cashback of ₹5,000 on SBI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-vx300-256r-6m',
            variantId: 'var-vx300-256-red',
            tenureMonths: 6,
            monthlyAmount: 14999,
            interestRate: 0,
            cashbackAmount: 5000,
            cashbackNote: 'Additional cashback of ₹5,000 on SBI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-vx300-256r-12m',
            variantId: 'var-vx300-256-red',
            tenureMonths: 12,
            monthlyAmount: 7499,
            interestRate: 0,
            cashbackAmount: 5000,
            cashbackNote: 'Additional cashback of ₹5,000 on SBI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-vx300-256r-24m',
            variantId: 'var-vx300-256-red',
            tenureMonths: 24,
            monthlyAmount: 4156,
            interestRate: 10.0,
            cashbackAmount: 5000,
            cashbackNote: 'Additional cashback of ₹5,000 on SBI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-vx300-256r-36m',
            variantId: 'var-vx300-256-red',
            tenureMonths: 36,
            monthlyAmount: 3037,
            interestRate: 10.5,
            cashbackAmount: 5000,
            cashbackNote: 'Additional cashback of ₹5,000 on SBI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
      {
        id: 'var-vx300-512-black',
        productId: 'prod-vivo-x300-pro',
        label: '512GB / Titanium Black',
        storage: '512GB',
        color: 'Titanium Black',
        imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
        mrp: 109999,
        price: 99999,
        stock: 30,
        emiPlans: [
          {
            id: 'emi-vx300-512b-3m',
            variantId: 'var-vx300-512-black',
            tenureMonths: 3,
            monthlyAmount: 33333,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Additional cashback of ₹6,000',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-vx300-512b-6m',
            variantId: 'var-vx300-512-black',
            tenureMonths: 6,
            monthlyAmount: 16666,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Additional cashback of ₹6,000',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-vx300-512b-12m',
            variantId: 'var-vx300-512-black',
            tenureMonths: 12,
            monthlyAmount: 8333,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Additional cashback of ₹6,000',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
  {
    id: 'prod-iqoo-13-5g',
    slug: 'iqoo-13-5g',
    name: 'iQOO 13 5G',
    brand: 'iQOO',
    description: 'Monster performance powered by Snapdragon 8 Elite, 2K 144Hz AMOLED display, Q2 supercomputing gaming chip, and 120W FlashCharge.',
    createdAt: new Date('2026-02-18T00:00:00Z'),
    variants: [
      {
        id: 'var-iq13-256-mint',
        productId: 'prod-iqoo-13-5g',
        label: '256GB / Legend Mint',
        storage: '256GB',
        color: 'Legend Mint',
        imageUrl: 'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=800&q=80',
        mrp: 64999,
        price: 54999,
        stock: 65,
        emiPlans: [
          {
            id: 'emi-iq13-256m-3m',
            variantId: 'var-iq13-256-mint',
            tenureMonths: 3,
            monthlyAmount: 18333,
            interestRate: 0,
            cashbackAmount: 3500,
            cashbackNote: 'Instant cashback of ₹3,500 on ICICI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-iq13-256m-6m',
            variantId: 'var-iq13-256-mint',
            tenureMonths: 6,
            monthlyAmount: 9166,
            interestRate: 0,
            cashbackAmount: 3500,
            cashbackNote: 'Instant cashback of ₹3,500 on ICICI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-iq13-256m-12m',
            variantId: 'var-iq13-256-mint',
            tenureMonths: 12,
            monthlyAmount: 4583,
            interestRate: 0,
            cashbackAmount: 3500,
            cashbackNote: 'Instant cashback of ₹3,500 on ICICI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-iq13-256m-24m',
            variantId: 'var-iq13-256-mint',
            tenureMonths: 24,
            monthlyAmount: 2536,
            interestRate: 9.5,
            cashbackAmount: 3500,
            cashbackNote: 'Instant cashback of ₹3,500 on ICICI/HDFC',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
      {
        id: 'var-iq13-512-black',
        productId: 'prod-iqoo-13-5g',
        label: '512GB / Alpha Black',
        storage: '512GB',
        color: 'Alpha Black',
        imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
        mrp: 71999,
        price: 61999,
        stock: 45,
        emiPlans: [
          {
            id: 'emi-iq13-512b-3m',
            variantId: 'var-iq13-512-black',
            tenureMonths: 3,
            monthlyAmount: 20666,
            interestRate: 0,
            cashbackAmount: 4000,
            cashbackNote: 'Instant cashback of ₹4,000',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-iq13-512b-6m',
            variantId: 'var-iq13-512-black',
            tenureMonths: 6,
            monthlyAmount: 10333,
            interestRate: 0,
            cashbackAmount: 4000,
            cashbackNote: 'Instant cashback of ₹4,000',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
  {
    id: 'prod-motorola-razr-50-ultra',
    slug: 'motorola-razr-50-ultra',
    name: 'Motorola Razr 50 Ultra',
    brand: 'Motorola',
    description: 'Iconic flip smartphone with industry-largest 4.0-inch external pOLED display, Snapdragon 8s Gen 3, and IPX8 water resistance.',
    createdAt: new Date('2026-02-15T00:00:00Z'),
    variants: [
      {
        id: 'var-razr50-512-white',
        productId: 'prod-motorola-razr-50-ultra',
        label: '512GB / Peach Fuzz White',
        storage: '512GB',
        color: 'Peach Fuzz White',
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
        mrp: 109999,
        price: 89999,
        stock: 35,
        emiPlans: [
          {
            id: 'emi-razr50-512w-3m',
            variantId: 'var-razr50-512-white',
            tenureMonths: 3,
            monthlyAmount: 29999,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000 on Moto Exchange',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-razr50-512w-6m',
            variantId: 'var-razr50-512-white',
            tenureMonths: 6,
            monthlyAmount: 14999,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000 on Moto Exchange',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-razr50-512w-12m',
            variantId: 'var-razr50-512-white',
            tenureMonths: 12,
            monthlyAmount: 7499,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000 on Moto Exchange',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-razr50-512w-24m',
            variantId: 'var-razr50-512-white',
            tenureMonths: 24,
            monthlyAmount: 3749,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000 on Moto Exchange',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-razr50-512w-36m',
            variantId: 'var-razr50-512-white',
            tenureMonths: 36,
            monthlyAmount: 3037,
            interestRate: 10.5,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000 on Moto Exchange',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
      {
        id: 'var-razr50-512-blue',
        productId: 'prod-motorola-razr-50-ultra',
        label: '512GB / Midnight Blue',
        storage: '512GB',
        color: 'Midnight Blue',
        imageUrl: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=80',
        mrp: 109999,
        price: 89999,
        stock: 25,
        emiPlans: [
          {
            id: 'emi-razr50-512b-6m',
            variantId: 'var-razr50-512-blue',
            tenureMonths: 6,
            monthlyAmount: 14999,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-razr50-512b-12m',
            variantId: 'var-razr50-512-blue',
            tenureMonths: 12,
            monthlyAmount: 7499,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Additional cashback of ₹7,000',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
  {
    id: 'prod-ipad-pro-m4-11',
    slug: 'ipad-pro-m4-11',
    name: 'iPad Pro M4 (11-inch)',
    brand: 'Apple',
    description: 'Impossibly thin design powered by Apple M4 chip, Ultra Retina XDR display with Tandem OLED technology, and Apple Pencil Pro support.',
    createdAt: new Date('2026-02-12T00:00:00Z'),
    variants: [
      {
        id: 'var-[#ipad-256-black]',
        productId: 'prod-ipad-pro-m4-11',
        label: '256GB / Space Black',
        storage: '256GB',
        color: 'Space Black',
        imageUrl: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
        mrp: 99900,
        price: 94900,
        stock: 50,
        emiPlans: [
          {
            id: 'emi-ipad-256b-3m',
            variantId: 'var-[#ipad-256-black]',
            tenureMonths: 3,
            monthlyAmount: 31633,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ipad-256b-6m',
            variantId: 'var-[#ipad-256-black]',
            tenureMonths: 6,
            monthlyAmount: 15816,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ipad-256b-12m',
            variantId: 'var-[#ipad-256-black]',
            tenureMonths: 12,
            monthlyAmount: 7908,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ipad-256b-24m',
            variantId: 'var-[#ipad-256-black]',
            tenureMonths: 24,
            monthlyAmount: 4385,
            interestRate: 10.0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ipad-256b-36m',
            variantId: 'var-[#ipad-256-black]',
            tenureMonths: 36,
            monthlyAmount: 3203,
            interestRate: 10.5,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
      {
        id: 'var-[#ipad-512-silver]',
        productId: 'prod-ipad-pro-m4-11',
        label: '512GB / Silver',
        storage: '512GB',
        color: 'Silver',
        imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
        mrp: 119900,
        price: 114900,
        stock: 30,
        emiPlans: [
          {
            id: 'emi-ipad-512s-3m',
            variantId: 'var-[#ipad-512-silver]',
            tenureMonths: 3,
            monthlyAmount: 38300,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Instant cashback of ₹7,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ipad-512s-6m',
            variantId: 'var-[#ipad-512-silver]',
            tenureMonths: 6,
            monthlyAmount: 19150,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Instant cashback of ₹7,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ipad-512s-12m',
            variantId: 'var-[#ipad-512-silver]',
            tenureMonths: 12,
            monthlyAmount: 9575,
            interestRate: 0,
            cashbackAmount: 7000,
            cashbackNote: 'Instant cashback of ₹7,000 on HDFC Bank',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
  {
    id: 'prod-iphone-17-pro',
    slug: 'iphone-17-pro',
    name: 'iPhone 17 Pro',
    brand: 'Apple',
    description: 'The ultimate iPhone engineered with an aerospace-grade titanium frame, groundbreaking A19 Pro chip, and revolutionary camera capabilities.',
    createdAt: new Date('2026-01-15T00:00:00Z'),
    variants: [
      {
        id: 'var-iphone-17-256-orange',
        productId: 'prod-iphone-17-pro',
        label: '256GB / Orange',
        storage: '256GB',
        color: 'Orange',
        imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=800&q=80',
        mrp: 134900,
        price: 127400,
        stock: 50,
        emiPlans: [
          {
            id: 'emi-ip17-256o-3m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 3,
            monthlyAmount: 42467,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256o-6m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 6,
            monthlyAmount: 21233,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256o-12m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 12,
            monthlyAmount: 10617,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256o-24m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 24,
            monthlyAmount: 5308,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256o-36m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 36,
            monthlyAmount: 4297,
            interestRate: 10.5,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256o-48m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 48,
            monthlyAmount: 3385,
            interestRate: 10.5,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256o-60m',
            variantId: 'var-iphone-17-256-orange',
            tenureMonths: 60,
            monthlyAmount: 2842,
            interestRate: 10.5,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
      {
        id: 'var-iphone-17-256-silver',
        productId: 'prod-iphone-17-pro',
        label: '256GB / Silver',
        storage: '256GB',
        color: 'Silver',
        imageUrl: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=800&q=80',
        mrp: 134900,
        price: 127400,
        stock: 45,
        emiPlans: [
          {
            id: 'emi-ip17-256s-3m',
            variantId: 'var-iphone-17-256-silver',
            tenureMonths: 3,
            monthlyAmount: 42467,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256s-6m',
            variantId: 'var-iphone-17-256-silver',
            tenureMonths: 6,
            monthlyAmount: 21233,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-ip17-256s-12m',
            variantId: 'var-iphone-17-256-silver',
            tenureMonths: 12,
            monthlyAmount: 10617,
            interestRate: 0,
            cashbackAmount: 7500,
            cashbackNote: 'Additional cashback of ₹7,500',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
  {
    id: 'prod-galaxy-s25-ultra',
    slug: 'samsung-galaxy-s25-ultra',
    name: 'Samsung Galaxy S25 Ultra',
    brand: 'Samsung',
    description: 'Empowered by Galaxy AI with futuristic 200MP Quad Telephoto camera, titanium frame, and integrated S-Pen productivity.',
    createdAt: new Date('2026-02-01T00:00:00Z'),
    variants: [
      {
        id: 'var-s25u-256-black',
        productId: 'prod-galaxy-s25-ultra',
        label: '256GB / Titanium Black',
        storage: '256GB',
        color: 'Titanium Black',
        imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=800&q=80',
        mrp: 129999,
        price: 119999,
        stock: 60,
        emiPlans: [
          {
            id: 'emi-s25u-256b-3m',
            variantId: 'var-s25u-256-black',
            tenureMonths: 3,
            monthlyAmount: 40000,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC/ICICI cards',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-s25u-256b-6m',
            variantId: 'var-s25u-256-black',
            tenureMonths: 6,
            monthlyAmount: 20000,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC/ICICI cards',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-s25u-256b-12m',
            variantId: 'var-s25u-256-black',
            tenureMonths: 12,
            monthlyAmount: 10000,
            interestRate: 0,
            cashbackAmount: 6000,
            cashbackNote: 'Instant cashback of ₹6,000 on HDFC/ICICI cards',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
  {
    id: 'prod-oneplus-13',
    slug: 'oneplus-13',
    name: 'OnePlus 13',
    brand: 'OnePlus',
    description: 'Extreme speed meets Hasselblad photography, 6000mAh Glacier battery, and 2K 120Hz ProXDR display.',
    createdAt: new Date('2026-02-10T00:00:00Z'),
    variants: [
      {
        id: 'var-op13-256-midnight',
        productId: 'prod-oneplus-13',
        label: '256GB / Midnight Ocean',
        storage: '256GB',
        color: 'Midnight Ocean',
        imageUrl: 'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=800&q=80',
        mrp: 69999,
        price: 64999,
        stock: 75,
        emiPlans: [
          {
            id: 'emi-op13-256m-3m',
            variantId: 'var-op13-256-midnight',
            tenureMonths: 3,
            monthlyAmount: 21666,
            interestRate: 0,
            cashbackAmount: 3000,
            cashbackNote: 'Cashback ₹3,000 on Axis/ICICI',
            fundedBy: 'Mutual Fund SIP',
          },
          {
            id: 'emi-op13-256m-6m',
            variantId: 'var-op13-256-midnight',
            tenureMonths: 6,
            monthlyAmount: 10833,
            interestRate: 0,
            cashbackAmount: 3000,
            cashbackNote: 'Cashback ₹3,000 on Axis/ICICI',
            fundedBy: 'Mutual Fund SIP',
          },
        ],
      },
    ],
  },
];
